services:
  - type: web
    name: thesocialfootball-owner-portal
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: thesocialfootball-db
          property: connectionString
      - key: ADMIN_EMAIL
        value: "mustafaduman7855@gmail.com"
databases:
  - name: thesocialfootball-db
    plan: free
